/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.oclinchoco.ReferenceTable;
import org.chocosolver.solver.Model;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        int numA = 10; int cardA2B=3;
        int numB = 23; int cardB2A=1;

        Model csp = new Model();

        ReferenceTable a2b = new ReferenceTable(csp,numA,cardA2B,numB);
        ReferenceTable b2a = new ReferenceTable(csp,numB,cardB2A,numA);
    }
}
