/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.oclinchoco.*;
import org.oclinchoco.CSP;
import org.oclinchoco.ReferenceTable;
import org.oclinchoco.NavCSP;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        int numA = 10; int minCardA2B=0; int maxCardA2B=3;
        int numB = 23; int minCardB2C=0; int maxCardB2C=1;
        int numC = 3;

        CSP csp = new CSP();

        ReferenceTable a2b = new ReferenceTable(csp,numA,maxCardA2B,minCardA2B,numB);
        ReferenceTable b2c = new ReferenceTable(csp,numC,maxCardB2C,minCardB2C,numC);
        NavCSP a12b2c = new NavCSP(csp,a2b.adjList(1),b2c);
    }
}
